name: Measure coverage

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      actions: write
      checks: write
      contents: write
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: checkout
        uses: actions/checkout@v4

      - name: Run Coverage
        run: |
          chmod +x gradlew
          ./gradlew jacocoTestReport

      - name: Add coverage to PR
        id: jacoco
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_URL: ${{ github.event.pull_request.comments_url }}
          REPORT_PATHS: ${{ github.workspace }}/**/controller/build/reports/jacoco/test/jacocoTestReport.xml,${{ github.workspace }}/**/model/build/reports/jacoco/test/jacocoTestReport.xml,${{ github.workspace }}/**/view/build/reports/jacoco/test/jacocoTestReport.xml
        run: |
          whoami
          ls -lha ./.github/workflows/jacoco-report.main.kts
          git fetch
          git checkout $GITHUB_HEAD_REF
          ./.github/workflows/jacoco-report.main.kts