name: Measure coverage

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      actions: write
      checks: write
      contents: write
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: checkout
        uses: actions/checkout@v4

      - name: Run Coverage
        run: |
          chmod +x gradlew
          ./gradlew jacocoTestReport

      - name: Add coverage to PR
        id: jacoco
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_URL: ${{ github.event.pull_request.html_url }}
          PR_NUMBER: ${{ github.event.number }}
          OUTPUT_FILE_PATH: /tmp/comment
          REPORT_PATHS: ./controller/build/reports/jacoco/test/jacocoTestReport.xml,./model/build/reports/jacoco/test/jacocoTestReport.xml,./view/build/reports/jacoco/test/jacocoTestReport.xml
        run: |
          chmod u+x ./.github/workflows/jacoco-report.main.kts
          git fetch
          git checkout $GITHUB_HEAD_REF
          ./.github/workflows/jacoco-report.main.kts
          gh pr comment "${PR_NUMBER}" -F ${OUTPUT_FILE_PATH}